#!/bin/sh
set -e
git --work-tree=../build reset --hard master
make -C ../build install prefix= datadir= DESTDIR=../htdocs
sudo -u staticsync /usr/local/bin/static-update-component timeline.debian.net
